// Mock Data matching SciCollab application specification

const researchers = [
  { 
    id: 1, 
    name: 'Dr. Sarah Chen', 
    title: 'Associate Professor', 
    department: 'Computer Science', 
    institution: 'MIT', 
    avatar: 'SC', 
    skills: ['Machine Learning', 'NLP', 'Data Mining'], 
    interests: ['AI Ethics', 'Federated Learning'], 
    publications: 42, 
    projects: 3, 
    conferences: 12, 
    collaborators: 18, 
    email: 'schen@mit.edu', 
    phone: '+1 617-253-0001', 
    bio: 'Specializes in large-scale machine learning systems and natural language processing with a focus on fairness and interpretability.', 
    hIndex: 19, 
    citations: 2840 
  },
  { 
    id: 2, 
    name: 'Prof. James Okafor', 
    title: 'Full Professor', 
    department: 'Biomedical Engineering', 
    institution: 'Stanford University', 
    avatar: 'JO', 
    skills: ['Genomics', 'Bioinformatics', 'CRISPR'], 
    interests: ['Gene Therapy', 'Precision Medicine'], 
    publications: 87, 
    projects: 5, 
    conferences: 22, 
    collaborators: 31, 
    email: 'jokafor@stanford.edu', 
    phone: '+1 650-723-0002', 
    bio: 'Pioneering research in CRISPR-based therapies and computational genomics for rare disease treatment.', 
    hIndex: 34, 
    citations: 8120 
  },
  { 
    id: 3, 
    name: 'Dr. Elena Vasquez', 
    title: 'Research Scientist', 
    department: 'Physics', 
    institution: 'Caltech', 
    avatar: 'EV', 
    skills: ['Quantum Computing', 'Condensed Matter', 'Spectroscopy'], 
    interests: ['Quantum Error Correction', 'Topological Materials'], 
    publications: 29, 
    projects: 2, 
    conferences: 9, 
    collaborators: 14, 
    email: 'evasquez@caltech.edu', 
    phone: '+1 626-395-0003', 
    bio: 'Working on the intersection of quantum information theory and condensed matter physics.', 
    hIndex: 11, 
    citations: 1150 
  },
  { 
    id: 4, 
    name: 'Dr. Marcus Webb', 
    title: 'Assistant Professor', 
    department: 'Environmental Science', 
    institution: 'UC Berkeley', 
    avatar: 'MW', 
    skills: ['Climate Modeling', 'Remote Sensing', 'GIS'], 
    interests: ['Carbon Sequestration', 'Ocean Acidification'], 
    publications: 21, 
    projects: 4, 
    conferences: 8, 
    collaborators: 22, 
    email: 'mwebb@berkeley.edu', 
    phone: '+1 510-642-0004', 
    bio: 'Developing high-resolution climate models to predict regional impacts of global warming.', 
    hIndex: 9, 
    citations: 640 
  },
  { 
    id: 5, 
    name: 'Prof. Aisha Nkosi', 
    title: 'Distinguished Professor', 
    department: 'Sociology', 
    institution: 'University of Chicago', 
    avatar: 'AN', 
    skills: ['Quantitative Research', 'Survey Methods', 'Urban Studies'], 
    interests: ['Inequality', 'Health Disparities'], 
    publications: 63, 
    projects: 6, 
    conferences: 18, 
    collaborators: 27, 
    email: 'ankosi@uchicago.edu', 
    phone: '+1 773-702-0005', 
    bio: 'Interdisciplinary scholar examining structural determinants of urban health and economic mobility.', 
    hIndex: 27, 
    citations: 4200 
  },
  { 
    id: 6, 
    name: 'Dr. Raj Patel', 
    title: 'Senior Research Fellow', 
    department: 'Materials Science', 
    institution: 'Carnegie Mellon University', 
    avatar: 'RP', 
    skills: ['Nanomaterials', 'Surface Chemistry', 'TEM'], 
    interests: ['Battery Technology', 'Photovoltaics'], 
    publications: 38, 
    projects: 3, 
    conferences: 14, 
    collaborators: 19, 
    email: 'rpatel@cmu.edu', 
    phone: '+1 412-268-0006', 
    bio: 'Engineering next-generation energy storage materials using bottom-up nanofabrication approaches.', 
    hIndex: 15, 
    citations: 1980 
  },
  { 
    id: 7, 
    name: 'Dr. Hana Müller', 
    title: 'Postdoctoral Researcher', 
    department: 'Cognitive Science', 
    institution: 'Johns Hopkins University', 
    avatar: 'HM', 
    skills: ['fMRI', 'Cognitive Neuroscience', 'Python'], 
    interests: ['Decision Making', 'Memory Consolidation'], 
    publications: 14, 
    projects: 2, 
    conferences: 7, 
    collaborators: 11, 
    email: 'hmuller@jhu.edu', 
    phone: '+1 410-516-0007', 
    bio: 'Investigating the neural substrates of episodic memory using multivariate fMRI analysis.', 
    hIndex: 6, 
    citations: 320 
  },
  { 
    id: 8, 
    name: 'Prof. Li Wei', 
    title: 'Professor', 
    department: 'Economics', 
    institution: 'Yale University', 
    avatar: 'LW', 
    skills: ['Econometrics', 'Game Theory', 'Policy Analysis'], 
    interests: ['International Trade', 'Labor Markets'], 
    publications: 55, 
    projects: 4, 
    conferences: 20, 
    collaborators: 24, 
    email: 'lwei@yale.edu', 
    phone: '+1 203-432-0008', 
    bio: 'Empirical economist studying the effects of globalization on labor market outcomes in developing economies.', 
    hIndex: 22, 
    citations: 3560 
  }
];

const publications = [
  { id: 1, title: 'Federated Learning with Differential Privacy for Biomedical Data Sharing', authors: [1, 2], type: 'Journal', venue: 'Nature Machine Intelligence', year: 2024, status: 'Published', citations: 127 },
  { id: 2, title: 'Quantum Error Correction Using Topological Codes on Near-Term Devices', authors: [3], type: 'Journal', venue: 'Physical Review Letters', year: 2024, status: 'Published', citations: 43 },
  { id: 3, title: 'High-Resolution Regional Climate Projections Under SSP5-8.5 Scenario', authors: [4], type: 'Journal', venue: 'Nature Climate Change', year: 2023, status: 'Published', citations: 89 },
  { id: 4, title: 'CRISPR-Cas9 Genome Editing Efficiency in Primary Human T Cells', authors: [2], type: 'Journal', venue: 'Cell', year: 2024, status: 'Submitted', citations: 0 },
  { id: 5, title: 'Urban Neighborhood Effects on Cardiovascular Outcomes: A Multi-City Study', authors: [5], type: 'Journal', venue: 'JAMA Internal Medicine', year: 2023, status: 'Published', citations: 201 },
  { id: 6, title: 'Solid-State Electrolytes for High-Energy-Density Lithium Batteries', authors: [6], type: 'Conference', venue: 'ACS Energy Letters', year: 2024, status: 'Published', citations: 38 },
  { id: 7, title: 'Neural Correlates of Prospective Memory Encoding During Natural Behavior', authors: [7], type: 'Journal', venue: 'Journal of Neuroscience', year: 2023, status: 'Published', citations: 22 },
  { id: 8, title: 'Global Value Chains and Labor Market Polarization in Emerging Economies', authors: [8], type: 'Journal', venue: 'American Economic Review', year: 2024, status: 'Draft', citations: 0 },
  { id: 9, title: 'Transformer Architectures for Low-Resource Scientific Text Classification', authors: [1], type: 'Conference', venue: 'ACL 2024', year: 2024, status: 'Published', citations: 56 },
  { id: 10, title: 'Photovoltaic Efficiency Enhancement via Plasmonic Nanostructure Integration', authors: [6, 3], type: 'Journal', venue: 'Advanced Energy Materials', year: 2023, status: 'Archived', citations: 74 }
];

const institutions = [
  { id: 1, name: 'Massachusetts Institute of Technology', type: 'University', country: 'USA', researchers: 312, publications: 1840, status: 'Active', established: 1861 },
  { id: 2, name: 'Stanford University', type: 'University', country: 'USA', researchers: 289, publications: 2120, status: 'Active', established: 1885 },
  { id: 3, name: 'California Institute of Technology', type: 'University', country: 'USA', researchers: 178, publications: 940, status: 'Active', established: 1891 },
  { id: 4, name: 'University of California, Berkeley', type: 'University', country: 'USA', researchers: 423, publications: 2560, status: 'Active', established: 1868 },
  { id: 5, name: 'University of Chicago', type: 'University', country: 'USA', researchers: 201, publications: 1120, status: 'Active', established: 1890 },
  { id: 6, name: 'Carnegie Mellon University', type: 'University', country: 'USA', researchers: 167, publications: 890, status: 'Active', established: 1900 },
  { id: 7, name: 'Johns Hopkins University', type: 'University', country: 'USA', researchers: 234, publications: 1340, status: 'Active', established: 1876 },
  { id: 8, name: 'Max Planck Institute', type: 'Research Institute', country: 'Germany', researchers: 98, publications: 620, status: 'Active', established: 1911 },
  { id: 9, name: 'European Research Council', type: 'Funding Body', country: 'Belgium', researchers: 0, publications: 0, status: 'Active', established: 2007 }
];
